name: Deploy React App to GH-Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Grab your code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install deps (npm install rather than npm ci)
      - name: Install dependencies
        run: npm install

      # 4. Build your app
      - name: Build
        run: npm run build

      # 5. Deploy to github pages
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PAGES_PAT }}    # your PAT
          publish_branch: gh-pages
          publish_dir: ./build
