name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Set up Node & install deps
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci

      # Build (this also runs `postbuild`)
      - name: Build production bundle
        run: npm run build

      # Deploy the build/ folder to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          # This built-in token has write access to this repo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Folder to publish
          publish_dir: build
          # Branch to push the static output to
          publish_branch: gh-pages
          # Create as an orphan branch so it's completely rebuilt every time
          force_orphan: true
          # Remove old files (keep the branch clean)
          keep_files: false
